# Generated by Django 2.0.3 on 2018-04-09 05:59

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180408_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='restaurantuser',
            managers=[
                ('custom', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='city',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
